# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionObs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.BooleanField(default=False)),
                ('observation', models.TextField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.Mission')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_type', to='projet.Type'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cl_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_zone', to='projet.Zone'),
        ),
    ]
