# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_auto_20160321_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='observation',
            field=models.TextField(default='a'),
        ),
    ]
