# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_type_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cl_zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='zone',
            name='paths',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='type',
            name='icone',
            field=models.ImageField(blank=True, upload_to='images/icones'),
        ),
    ]
