# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0006_auto_20160407_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='couleur',
            field=models.CharField(default='green', max_length=25),
        ),
        migrations.AlterField(
            model_name='zone',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='paths',
            field=models.TextField(),
        ),
    ]
