# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0007_auto_20160407_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone_name',
            new_name='name',
        ),
    ]
