# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0008_auto_20160411_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('couleur', models.CharField(max_length=25)),
            ],
        ),
    ]
