# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0012_remove_zone_couleur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='ag_adr',
            new_name='adr',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='ag_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='ag_login',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='ag_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='ag_pwd',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='ag_tel',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='com_adr',
            new_name='adr',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='com_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='com_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='commercial',
            old_name='com_tel',
            new_name='tel',
        ),
    ]
