# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0014_auto_20160418_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='lieux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projet.Client'),
        ),
    ]
