# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0016_mission_date_exe'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='time_do',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='time_exe',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_do',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mission',
            name='date_exe',
            field=models.DateField(blank=True, null=True),
        ),
    ]
