# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0017_auto_20160503_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='typemission',
            field=models.ManyToManyField(to='projet.TypeMission'),
        ),
        migrations.RemoveField(
            model_name='programme',
            name='lieux',
        ),
        migrations.AddField(
            model_name='programme',
            name='lieux',
            field=models.ManyToManyField(to='projet.Client'),
        ),
    ]
