# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0018_auto_20160503_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='lieux',
        ),
        migrations.AddField(
            model_name='programme',
            name='lieux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projet.Client'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='timing',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='programme',
            name='typemission',
        ),
        migrations.AddField(
            model_name='programme',
            name='typemission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projet.TypeMission'),
        ),
    ]
