# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0021_auto_20160503_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icone',
            field=models.FileField(blank=True, upload_to='images/icones'),
        ),
    ]
