# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0022_auto_20160510_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='icone',
            field=models.ImageField(blank=True, upload_to='images/icones'),
        ),
    ]
