# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0023_auto_20160510_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom complet')),
                ('prenom', models.CharField(max_length=100, verbose_name='prenoms ')),
                ('age', models.IntegerField(default=10)),
            ],
        ),
    ]
